# workflow 이름 설정
name: Front-end Deployment

# workflow를 트리거하는 이벤트 설정
on:
  push:
    # FE_develop 브랜치에 푸시할 때 실행
    branches: ["FE_develop"]

# 실행할 jobs 설정
jobs:
  # job 이름 설정
  build-and-deploy:
    # Ubuntu 환경에서 실행
    runs-on: ubuntu-latest

    steps:
      # 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker 이미지 빌더 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # NCP Container Registry에 접속
      - name: Login to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      # Docker 이미지 빌드 및 NCP Container Registry에 등록
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/mafiacamp-fe
          context: ./FE
          build-args: |
            ARG_NEXT_PUBLIC_BACKEND_URL=${{ secrets.BACKEND_URL }}
            ARG_BACKEND_API_URL=${{ secrets.BACKEND_API_URL }}
            ARG_NEXT_PUBLIC_BACKEND_API_URL=${{ secrets.NEXT_PUBLIC_BACKEND_API_URL }}

      # ssh 원격 접속을 통해 빌드 파일 실행하기
      - name: Executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          script: |
            docker stop mafiacamp-fe || true
            docker rm mafiacamp-fe || true
            docker image prune || true
            docker pull ${{ secrets.NCP_PRIVATE_ENDPOINT }}/mafiacamp-fe
            docker run -p 3000:3000 -d --restart unless-stopped --name mafiacamp-fe ${{ secrets.NCP_PRIVATE_ENDPOINT }}/mafiacamp-fe
